# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'snschat' do
  
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!

  pod 'Socket.IO-Client-Swift', '~> 2.0.6' # Or latest version

  pod "SwiftyJSON", ">= 2.2"

end

target 'snschatTests' do

end

